version: '3.9'

services:
  app:
    image: flarecast-user-service:latest  # Replace with your app's image name
    container_name: flarecast-user-service
    env_file:
      - path: ./.env
        required: true
      - path: .env.docker
        required: true
    ports:
      - "4001:4001"  # Map container port 4001 to host port 4001

