apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-app
  labels:
    app: user-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
      - name: user-app
        image: ananthutd2003/flarecast-user-service
        ports:
        - containerPort: 4000 
        env:
        - name: PORT
          value: "4000"
        - name: NODE_ENV
          value: "development"
        - name: REFRESH_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: REFRESH_TOKEN_SECRET
        - name: ACCESS_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: REFRESH_TOKEN_SECRET
        # kafka
        - name: KAFKA_BROKER 
          value: kafka:9092 
        - name: KAFKA_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: KAFKA_USERNAME
        - name: KAFKA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: KAFKA_PASSWORD
        # DB
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DATABASE_URL
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: GOOGLE_CLIENT_ID
        command: ["sh", "-c", "pnpm prisma:migrate:prod && pnpm docker-dev"]
        resources:
          requests:
            memory: "128Mi"  # Reduced from 256Mi
            cpu: "200m"      # Reduced from 500m
          limits:
            memory: "256Mi"  # Reduced from 512Mi
            cpu: "400m"      # Reduced from 1
---
apiVersion: v1
kind: Service
metadata:
  name: user-app
spec:
  selector:
    app: user-app
  ports:
  - protocol: TCP
    targetPort: 4000
    port: 4001
  type: NodePort
