apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: user-db
  labels:
    app: user-db
spec:
  serviceName: user-db
  replicas: 1
  selector:
    matchLabels:
      app: user-db
  template:
    metadata:
      labels:
        app: user-db
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: name
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: user-db-storage
        resources:
          requests:
            memory: "128Mi"  # Reduced from 256Mi
            cpu: "200m"      # Reduced from 500m
          limits:
            memory: "256Mi"  # Reduced from 512Mi
            cpu: "400m"      # Reduced from 1
      volumes:
      - name: user-db-storage
        persistentVolumeClaim:
          claimName: user-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: user-db
spec:
  selector:
    app: user-db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
