apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-db-pv
  labels:
    storage: postgres
spec:
  capacity:
    storage: "128Mi"
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/postgres

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-db-pvc
spec:
  selector:
    matchLabels:
      storage: postgres
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
